spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/hhplus_chepter2
    username: root
    password: hhplus4613

  jpa:
    hibernate:
      ddl-auto: none

  logging:
    level:
      org.hibernate:
        type.descriptor.sql: trace
        SQL: DEBUG

