spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  data:
    redis:
      host: 127.0.0.1
      port: 6379

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/hhplus_chepter2
    username: root
    password: hhplus4613

  jpa:
    hibernate:
      ddl-auto: none

  logging:
    level:
      org.hibernate:
        type.descriptor.sql: trace
        SQL: DEBUG

